#!/bin/bash

# Transpile the TypeScript into CommonJS packaged JavaScript (using tsconfig.json settings).
tsc -p .

# Create a version for use in web browsers.
browserify src/browser.js -o lib/web/state.js

# minify the Web version.
minify lib/web/state.js > lib/web/state.min.js

cp lib/node/tree.js lib/web/tree.js